
image: rocker/verse:4.2.2

get_file:
  stage: build
  before_script:

  script:
    - git remote set-url origin https://${CI_USERNAME}:${CI_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    
    # 在 rocker 里执行代码
    # - Rscript MAIN.R 
    - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

  after_script:
    # push to origin branch
    - git add --all *
    - git commit -m 'download file'
    - git push origin HEAD:$CI_COMMIT_REF_NAME